[pytest]
addopts =
    --ignore auth0/test/management/test_actions.py
    --ignore auth0/test/management/test_auth0.py
    --ignore auth0/test/management/test_prompts.py
    --ignore auth0/test_async/test_async_auth0.py
    --ignore auth0/test_async/test_async_token_verifier.py
    --ignore auth0/test_async/test_asyncify.py
    --deselect auth0/test/management/test_atack_protection.py::TestAttackProtection::test_get_breached_password_detection
    --deselect auth0/test/management/test_atack_protection.py::TestAttackProtection::test_get_brute_force_protection
    --deselect auth0/test/management/test_atack_protection.py::TestAttackProtection::test_get_suspicious_ip_throttling
    --deselect auth0/test/management/test_atack_protection.py::TestAttackProtection::test_update_breached_password_detection
    --deselect auth0/test/management/test_atack_protection.py::TestAttackProtection::test_update_brute_force_protection
    --deselect auth0/test/management/test_atack_protection.py::TestAttackProtection::test_update_suspicious_ip_throttling
    --deselect auth0/test/management/test_blacklists.py::TestBlacklists::test_create
    --deselect auth0/test/management/test_blacklists.py::TestBlacklists::test_get
    --deselect auth0/test/management/test_branding.py::TestBranding::test_create_branding_theme
    --deselect auth0/test/management/test_branding.py::TestBranding::test_delete_branding_theme
    --deselect auth0/test/management/test_branding.py::TestBranding::test_delete_template_universal_login
    --deselect auth0/test/management/test_branding.py::TestBranding::test_get
    --deselect auth0/test/management/test_branding.py::TestBranding::test_get_branding_theme
    --deselect auth0/test/management/test_branding.py::TestBranding::test_get_default_branding_theme
    --deselect auth0/test/management/test_branding.py::TestBranding::test_get_template_universal_login
    --deselect auth0/test/management/test_branding.py::TestBranding::test_update
    --deselect auth0/test/management/test_branding.py::TestBranding::test_update_branding_theme
    --deselect auth0/test/management/test_client_credentials.py::TestClientCredentials::test_all
    --deselect auth0/test/management/test_client_credentials.py::TestClientCredentials::test_create
    --deselect auth0/test/management/test_client_credentials.py::TestClientCredentials::test_delete
    --deselect auth0/test/management/test_client_credentials.py::TestClientCredentials::test_get
    --deselect auth0/test/management/test_client_grants.py::TestClientGrants::test_all
    --deselect auth0/test/management/test_client_grants.py::TestClientGrants::test_create
    --deselect auth0/test/management/test_client_grants.py::TestClientGrants::test_delete
    --deselect auth0/test/management/test_client_grants.py::TestClientGrants::test_get_organizations
    --deselect auth0/test/management/test_client_grants.py::TestClientGrants::test_update
    --deselect auth0/test/management/test_clients.py::TestClients::test_all
    --deselect auth0/test/management/test_clients.py::TestClients::test_create
    --deselect auth0/test/management/test_clients.py::TestClients::test_delete
    --deselect auth0/test/management/test_clients.py::TestClients::test_get
    --deselect auth0/test/management/test_clients.py::TestClients::test_rotate_secret
    --deselect auth0/test/management/test_clients.py::TestClients::test_update
    --deselect auth0/test/management/test_connections.py::TestConnection::test_all
    --deselect auth0/test/management/test_connections.py::TestConnection::test_create
    --deselect auth0/test/management/test_connections.py::TestConnection::test_delete
    --deselect auth0/test/management/test_connections.py::TestConnection::test_delete_user_by_email
    --deselect auth0/test/management/test_connections.py::TestConnection::test_get
    --deselect auth0/test/management/test_connections.py::TestConnection::test_update
    --deselect auth0/test/management/test_custom_domains.py::TestCustomDomains::test_create_new
    --deselect auth0/test/management/test_custom_domains.py::TestCustomDomains::test_get_all
    --deselect auth0/test/management/test_custom_domains.py::TestCustomDomains::test_get_domain_by_id
    --deselect auth0/test/management/test_custom_domains.py::TestCustomDomains::test_verify
    --deselect auth0/test/management/test_device_credentials.py::TestDeviceCredentials::test_create
    --deselect auth0/test/management/test_device_credentials.py::TestDeviceCredentials::test_delete
    --deselect auth0/test/management/test_device_credentials.py::TestDeviceCredentials::test_get
    --deselect auth0/test/management/test_email_endpoints.py::TestClients::test_create
    --deselect auth0/test/management/test_email_endpoints.py::TestClients::test_get
    --deselect auth0/test/management/test_email_endpoints.py::TestClients::test_update
    --deselect auth0/test/management/test_emails.py::TestEmails::test_config
    --deselect auth0/test/management/test_emails.py::TestEmails::test_delete
    --deselect auth0/test/management/test_emails.py::TestEmails::test_get
    --deselect auth0/test/management/test_emails.py::TestEmails::test_update
    --deselect auth0/test/management/test_grants.py::TestGrants::test_delete
    --deselect auth0/test/management/test_grants.py::TestGrants::test_get_all
    --deselect auth0/test/management/test_guardian.py::TestGuardian::test_all_factors
    --deselect auth0/test/management/test_guardian.py::TestGuardian::test_create_enrollment_ticket
    --deselect auth0/test/management/test_guardian.py::TestGuardian::test_delete_enrollment
    --deselect auth0/test/management/test_guardian.py::TestGuardian::test_get_enrollment
    --deselect auth0/test/management/test_guardian.py::TestGuardian::test_get_factor_providers
    --deselect auth0/test/management/test_guardian.py::TestGuardian::test_get_templates
    --deselect auth0/test/management/test_guardian.py::TestGuardian::test_update_factor
    --deselect auth0/test/management/test_guardian.py::TestGuardian::test_update_factor_providers
    --deselect auth0/test/management/test_guardian.py::TestGuardian::test_update_templates
    --deselect auth0/test/management/test_hooks.py::TestRules::test_add_secret
    --deselect auth0/test/management/test_hooks.py::TestRules::test_all
    --deselect auth0/test/management/test_hooks.py::TestRules::test_create
    --deselect auth0/test/management/test_hooks.py::TestRules::test_delete
    --deselect auth0/test/management/test_hooks.py::TestRules::test_delete_secrets
    --deselect auth0/test/management/test_hooks.py::TestRules::test_get
    --deselect auth0/test/management/test_hooks.py::TestRules::test_get_secrets
    --deselect auth0/test/management/test_hooks.py::TestRules::test_update
    --deselect auth0/test/management/test_hooks.py::TestRules::test_update_secrets
    --deselect auth0/test/management/test_jobs.py::TestJobs::test_export_users
    --deselect auth0/test/management/test_jobs.py::TestJobs::test_get
    --deselect auth0/test/management/test_jobs.py::TestJobs::test_get_failed_job
    --deselect auth0/test/management/test_jobs.py::TestJobs::test_import_users
    --deselect auth0/test/management/test_jobs.py::TestJobs::test_verification_email
    --deselect auth0/test/management/test_log_streams.py::TestLogStreams::test_create
    --deselect auth0/test/management/test_log_streams.py::TestLogStreams::test_delete
    --deselect auth0/test/management/test_log_streams.py::TestLogStreams::test_get
    --deselect auth0/test/management/test_log_streams.py::TestLogStreams::test_list
    --deselect auth0/test/management/test_log_streams.py::TestLogStreams::test_update
    --deselect auth0/test/management/test_logs.py::TestLogs::test_get
    --deselect auth0/test/management/test_logs.py::TestLogs::test_search
    --deselect auth0/test/management/test_organizations.py::TestOrganizations::test_add_client_grant
    --deselect auth0/test/management/test_organizations.py::TestOrganizations::test_all_organization_connections
    --deselect auth0/test/management/test_organizations.py::TestOrganizations::test_all_organization_invitations
    --deselect auth0/test/management/test_organizations.py::TestOrganizations::test_all_organization_member_roles
    --deselect auth0/test/management/test_organizations.py::TestOrganizations::test_all_organization_members
    --deselect auth0/test/management/test_organizations.py::TestOrganizations::test_all_organizations
    --deselect auth0/test/management/test_organizations.py::TestOrganizations::test_create_organization
    --deselect auth0/test/management/test_organizations.py::TestOrganizations::test_create_organization_connection
    --deselect auth0/test/management/test_organizations.py::TestOrganizations::test_create_organization_invitation
    --deselect auth0/test/management/test_organizations.py::TestOrganizations::test_create_organization_member_roles
    --deselect auth0/test/management/test_organizations.py::TestOrganizations::test_create_organization_members
    --deselect auth0/test/management/test_organizations.py::TestOrganizations::test_delete_client_grant
    --deselect auth0/test/management/test_organizations.py::TestOrganizations::test_delete_organization
    --deselect auth0/test/management/test_organizations.py::TestOrganizations::test_delete_organization_connection
    --deselect auth0/test/management/test_organizations.py::TestOrganizations::test_delete_organization_invitation
    --deselect auth0/test/management/test_organizations.py::TestOrganizations::test_delete_organization_member_roles
    --deselect auth0/test/management/test_organizations.py::TestOrganizations::test_delete_organization_members
    --deselect auth0/test/management/test_organizations.py::TestOrganizations::test_get_client_grants
    --deselect auth0/test/management/test_organizations.py::TestOrganizations::test_get_organization
    --deselect auth0/test/management/test_organizations.py::TestOrganizations::test_get_organization_by_name
    --deselect auth0/test/management/test_organizations.py::TestOrganizations::test_get_organization_connection
    --deselect auth0/test/management/test_organizations.py::TestOrganizations::test_get_organization_invitation
    --deselect auth0/test/management/test_organizations.py::TestOrganizations::test_update_organization
    --deselect auth0/test/management/test_organizations.py::TestOrganizations::test_update_organization_connection
    --deselect auth0/test/management/test_resource_servers.py::TestResourceServers::test_create
    --deselect auth0/test/management/test_resource_servers.py::TestResourceServers::test_delete
    --deselect auth0/test/management/test_resource_servers.py::TestResourceServers::test_get
    --deselect auth0/test/management/test_resource_servers.py::TestResourceServers::test_get_all
    --deselect auth0/test/management/test_resource_servers.py::TestResourceServers::test_update
    --deselect auth0/test/management/test_roles.py::TestRoles::test_add_permissions
    --deselect auth0/test/management/test_roles.py::TestRoles::test_add_users
    --deselect auth0/test/management/test_roles.py::TestRoles::test_create
    --deselect auth0/test/management/test_roles.py::TestRoles::test_delete
    --deselect auth0/test/management/test_roles.py::TestRoles::test_get
    --deselect auth0/test/management/test_roles.py::TestRoles::test_list
    --deselect auth0/test/management/test_roles.py::TestRoles::test_list_permissions
    --deselect auth0/test/management/test_roles.py::TestRoles::test_list_users
    --deselect auth0/test/management/test_roles.py::TestRoles::test_remove_permissions
    --deselect auth0/test/management/test_roles.py::TestRoles::test_update
    --deselect auth0/test/management/test_rules.py::TestRules::test_all
    --deselect auth0/test/management/test_rules.py::TestRules::test_create
    --deselect auth0/test/management/test_rules.py::TestRules::test_delete
    --deselect auth0/test/management/test_rules.py::TestRules::test_get
    --deselect auth0/test/management/test_rules.py::TestRules::test_update
    --deselect auth0/test/management/test_rules_configs.py::TestRulesConfigs::test_all
    --deselect auth0/test/management/test_rules_configs.py::TestRulesConfigs::test_set
    --deselect auth0/test/management/test_rules_configs.py::TestRulesConfigs::test_unset
    --deselect auth0/test/management/test_self_service_profiles.py::TestSelfServiceProfiles::test_all
    --deselect auth0/test/management/test_self_service_profiles.py::TestSelfServiceProfiles::test_create
    --deselect auth0/test/management/test_self_service_profiles.py::TestSelfServiceProfiles::test_create_sso_ticket
    --deselect auth0/test/management/test_self_service_profiles.py::TestSelfServiceProfiles::test_delete
    --deselect auth0/test/management/test_self_service_profiles.py::TestSelfServiceProfiles::test_get
    --deselect auth0/test/management/test_self_service_profiles.py::TestSelfServiceProfiles::test_get_custom_text
    --deselect auth0/test/management/test_self_service_profiles.py::TestSelfServiceProfiles::test_revoke_sso_ticket
    --deselect auth0/test/management/test_self_service_profiles.py::TestSelfServiceProfiles::test_update
    --deselect auth0/test/management/test_self_service_profiles.py::TestSelfServiceProfiles::test_update_custom_text
    --deselect auth0/test/management/test_stats.py::TestStats::test_active_users
    --deselect auth0/test/management/test_stats.py::TestStats::test_daily_stats
    --deselect auth0/test/management/test_tenants.py::TestTenants::test_get
    --deselect auth0/test/management/test_tenants.py::TestTenants::test_update
    --deselect auth0/test/management/test_tickets.py::TestTickets::test_email
    --deselect auth0/test/management/test_tickets.py::TestTickets::test_pswd
    --deselect auth0/test/management/test_user_blocks.py::TestUserBlocks::test_get
    --deselect auth0/test/management/test_user_blocks.py::TestUserBlocks::test_get_by_identifier
    --deselect auth0/test/management/test_user_blocks.py::TestUserBlocks::test_unblock
    --deselect auth0/test/management/test_user_blocks.py::TestUserBlocks::test_unblock_by_identifier
    --deselect auth0/test/management/test_users.py::TestUsers::test_add_permissions
    --deselect auth0/test/management/test_users.py::TestUsers::test_add_roles
    --deselect auth0/test/management/test_users.py::TestUsers::test_create
    --deselect auth0/test/management/test_users.py::TestUsers::test_create_authentication_method
    --deselect auth0/test/management/test_users.py::TestUsers::test_delete
    --deselect auth0/test/management/test_users.py::TestUsers::test_delete_authentication_method_by_id
    --deselect auth0/test/management/test_users.py::TestUsers::test_delete_authentication_methods
    --deselect auth0/test/management/test_users.py::TestUsers::test_delete_authenticators
    --deselect auth0/test/management/test_users.py::TestUsers::test_delete_multifactor
    --deselect auth0/test/management/test_users.py::TestUsers::test_delete_tokenset_by_id
    --deselect auth0/test/management/test_users.py::TestUsers::test_get
    --deselect auth0/test/management/test_users.py::TestUsers::test_get_authentication_method_by_id
    --deselect auth0/test/management/test_users.py::TestUsers::test_get_authentication_methods
    --deselect auth0/test/management/test_users.py::TestUsers::test_get_guardian_enrollments
    --deselect auth0/test/management/test_users.py::TestUsers::test_get_log_events
    --deselect auth0/test/management/test_users.py::TestUsers::test_invalidate_remembered_browsers
    --deselect auth0/test/management/test_users.py::TestUsers::test_link_user_account
    --deselect auth0/test/management/test_users.py::TestUsers::test_list
    --deselect auth0/test/management/test_users.py::TestUsers::test_list_organizations
    --deselect auth0/test/management/test_users.py::TestUsers::test_list_permissions
    --deselect auth0/test/management/test_users.py::TestUsers::test_list_roles
    --deselect auth0/test/management/test_users.py::TestUsers::test_list_tokensets
    --deselect auth0/test/management/test_users.py::TestUsers::test_regenerate_recovery_code
    --deselect auth0/test/management/test_users.py::TestUsers::test_remove_permissions
    --deselect auth0/test/management/test_users.py::TestUsers::test_remove_roles
    --deselect auth0/test/management/test_users.py::TestUsers::test_unlink_user_account
    --deselect auth0/test/management/test_users.py::TestUsers::test_update
    --deselect auth0/test/management/test_users.py::TestUsers::test_update_authentication_method_by_id
    --deselect auth0/test/management/test_users.py::TestUsers::test_update_authentication_methods
    --deselect auth0/test/management/test_users_by_email.py::TestUsersByEmail::test_search_users_by_email
