[pytest]
addopts =
    --deselect tests/test_authz_authorizer.py::TestAuthorizerWithMockedJWT::test__check_resource
    --deselect tests/test_aws_ssm.py::test__get_parameter__returns_value_fetched_from_aws
    --deselect tests/test_aws_ssm.py::test__get_parameter__returns_value_none_when_unexpected_response
    --deselect tests/test_aws_ssm.py::test__get_parameter__returns_value_none_when_parameter_not_found
