[pytest]
addopts =
    --deselect=tests/datamuse/test_api.py::DatamuseTestCase::test_suggest
    --deselect=tests/datamuse/test_api.py::DatamuseTestCase::test_near_rhymes
    --deselect=tests/datamuse/test_api.py::DatamuseTestCase::test_rhymes
    --deselect=tests/datamuse/test_api.py::DatamuseTestCase::test_set_max
    --deselect=tests/datamuse/test_api.py::DatamuseTestCase::test_sounds_like
