[pytest]
addopts =
    --deselect tests/test_argument_parser.py::test_multiple_value_for_single_parameter_error[param_names1-args1-kwargs1]
    --deselect tests/test_argument_parser.py::test_multiple_value_for_single_parameter_error[param_names3-args3-kwargs3]
    --deselect tests/test_argument_parser.py::test_multiple_value_for_single_parameter_error[param_names4-args4-kwargs4]
    --deselect tests/test_argument_parser.py::test_multiple_value_for_single_parameter_error[param_names5-args5-kwargs5]
    --deselect tests/test_argument_parser.py::test_unexpected_keyword_argument[param_names2-args2-kwargs2]
    --deselect tests/test_argument_parser.py::test_unexpected_keyword_argument[param_names9-args9-kwargs9]
    --deselect tests/test_argument_parser.py::test_unexpected_keyword_argument[param_names11-args11-kwargs11]
    --deselect tests/test_argument_parser.py::test_unwrapped_arg_counts[1-2-param_defs15]
    --deselect tests/test_argument_parser.py::test_unwrapped_arg_counts[0-2-param_defs16]
    --deselect tests/test_argument_parser.py::test_unwrapped_arg_counts[0-2-param_defs17]
    --deselect tests/test_argument_parser.py::test_unwrapped_arg_counts[1-3-param_defs19]
    --deselect tests/test_argument_parser.py::test_unwrapped_arg_counts[2-4-param_defs20]
    --deselect tests/test_argument_parser.py::test_unwrapped_arg_counts[2-5-param_defs21]
    --deselect tests/test_argument_parser.py::test_unwrapped_arg_counts[2-5-param_defs22]
    --deselect tests/test_argument_parser.py::test_unwrapped_arg_counts[3-6-param_defs23]
    --deselect tests/test_argument_parser.py::test_unwrapped_arg_counts[2-6-param_defs24]
    --deselect tests/test_argument_parser.py::test_unwrapped_arg_counts[2-4-param_defs25]
    --deselect tests/test_argument_parser.py::test_unwrapped_arg_counts[1-4-param_defs26]
    --deselect tests/test_argument_parser.py::test_unwrapped_arg_counts[3-5-param_defs27]
    --deselect tests/test_argument_parser.py::test_unwrapped_arg_counts[0-3-param_defs28]
    --deselect tests/test_argument_parser.py::test_unwrapped_arg_counts[0-3-param_defs29]
    --deselect tests/test_argument_parser.py::test_unwrapped_arg_counts[1-3-param_defs30]
    --deselect tests/test_argument_parser.py::test_unwrapped_arg_counts[3-14-param_defs31]
    --deselect tests/test_cache.py::TestDefaultFileCacheLocation::test_basic[DocumentCache]
    --deselect tests/test_cache.py::TestDefaultFileCacheLocation::test_basic[FileCache]
    --deselect tests/test_cache.py::TestDefaultFileCacheLocation::test_basic[ObjectCache]
    --deselect tests/test_cache.py::TestDefaultFileCacheLocation::test_remove_on_exit[True]
    --deselect tests/test_cache.py::TestDefaultFileCacheLocation::test_remove_on_exit[False]
    --deselect tests/test_input_parameters.py::TestUnsupportedParameterDefinitions::test_choice_containing_an_empty_sequence[False]
    --deselect tests/test_input_parameters.py::test_typed_parameters[param_names1]
    --deselect tests/test_input_parameters.py::test_typed_parameters[param_names2]
    --deselect tests/test_input_parameters.py::test_typed_parameters[param_names3]
    --deselect tests/test_input_parameters.py::test_unwrapped_parameter[xsd_type0]
    --deselect tests/test_input_parameters.py::test_unwrapped_parameter[xsd_type1]
    --deselect tests/test_input_parameters.py::test_unwrapped_parameter[xsd_type2]
    --deselect tests/test_input_parameters.py::test_unwrapped_parameter[xsd_type3]
    --deselect tests/test_input_parameters.py::test_unwrapped_parameter[xsd_type4]
    --deselect tests/test_input_parameters.py::test_unwrapped_parameter[xsd_type5]
    --deselect tests/test_input_parameters.py::test_unwrapped_parameter[xsd_type6]
    --deselect tests/test_input_parameters.py::test_unwrapped_parameter[xsd_type7]
    --deselect tests/test_input_parameters.py::test_unwrapped_parameter[xsd_type8]
    --deselect tests/test_input_parameters.py::test_unwrapped_parameter_part_name[parameters]
    --deselect tests/test_input_parameters.py::test_unwrapped_parameter_part_name[pipi]
    --deselect tests/test_reader.py::TestCacheItemNameMangling::test_inter_processes_persistence
