[pytest]
addopts =
	--ignore=tests/models/test_keras_model.py
	--ignore=tests/models/test_torch_model.py
	--ignore=tests/models/test_torch_module.py
	--deselect=tests/models/test_models.py::test_model_from_yaml[test_files/california_regression/torch_model.yml-TorchModel]
	--deselect=tests/models/test_models.py::test_model_from_yaml[test_files/california_regression/torch_module.yml-TorchModule]
	--deselect=tests/models/test_models.py::test_model_from_yaml[test_files/iris_classification/keras_model.yml-KerasModel]
	--deselect=tests/test_utils.py::test_variables_as_and_from_yaml
