[pytest]
addopts =
	--ignore=cosimulation/cver/test/test_all.py
	--ignore=cosimulation/icarus/test/test_all.py
	--ignore=cosimulation/icarus/test/test_gray.py
	--ignore=cosimulation/icarus/test/test_initial_value_bug.py
	--ignore=cosimulation/modelsim-win/test/test_all.py
	--ignore=cosimulation/modelsim/test/test_all.py
	--ignore=example/arith_lib/test_Dec.py
	--ignore=example/arith_lib/test_LeadZeroDet.py
	--ignore=example/cookbook/johnson/test_jc2.py
	--ignore=example/cookbook/stopwatch/test_TimeCount.py
	--ignore=example/cookbook/stopwatch/test_bcd2led.py
	--ignore=example/manual/test_bin2gray.py
	--ignore=example/manual/test_fsm.py
	--ignore=example/manual/test_inc.py
	--ignore=example/rs232/test_rs232.py
	--ignore=myhdl/test
	--ignore=scripts/benchmark/test_randgen.py
	--deselect=cosimulation/test/test_const_1.py::TestConst::test1
	--deselect=cosimulation/test/test_const_1.py::TestConst::test2
	--deselect=example/cookbook/bitonic/test_bitonic.py::test_bench
	--deselect=example/cookbook/sinecomp/test_SineComputer.py::test_bench
	--deselect=example/manual/test_gray_original.py::TestOriginalGrayCode::testOriginalGrayCode
	--deselect=example/manual/test_gray_properties.py::TestGrayCodeProperties::testSingleBitChange
	--deselect=example/manual/test_gray_properties.py::TestGrayCodeProperties::testUniqueCodeWords
	--deselect=example/manual/test_mux.py::test_mux
	--deselect=scripts/benchmark/test_findmax.py::test_findmax
	--deselect=scripts/benchmark/test_findmax_sigs.py::test_findmax
	--deselect=scripts/benchmark/test_lfsr24.py::test_lfsr24
	--deselect=scripts/benchmark/test_longdiv.py::test_longdiv
	--deselect=scripts/benchmark/test_longdiv_10.py::test_longdiv
	--deselect=scripts/benchmark/test_longdiv_11.py::test_longdiv
	--deselect=scripts/benchmark/test_longdiv_12.py::test_longdiv
	--deselect=scripts/benchmark/test_longdiv_13.py::test_longdiv
	--deselect=scripts/benchmark/test_longdiv_14.py::test_longdiv
	--deselect=scripts/benchmark/test_longdiv_15.py::test_longdiv
	--deselect=scripts/benchmark/test_longdiv_16.py::test_longdiv
	--deselect=scripts/benchmark/test_longdiv_17.py::test_longdiv
	--deselect=scripts/benchmark/test_longdiv_18.py::test_longdiv
	--deselect=scripts/benchmark/test_longdiv_9.py::test_longdiv
	--deselect=scripts/benchmark/test_timer.py::test_timer
	--deselect=scripts/benchmark/test_timer_array.py::test_timer_array
