name: Analyzes the data and generate a report.csv


permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      release-tag:
        description: 'The tag of the release to download logs from.'
        required: true
        type: string
      repositories:
        description: 'Space-separated list of repositories in the format owner/repo.'
        required: true
        type: string

jobs:
    analyze_data:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
            with:
              fetch-depth: 0
    
          - name: Setup working directories
            run: |
              mkdir -p ./projects/reports
            
          - name: Download files from multiple releases
            run: |
              for repo in ${{ github.event.inputs.repositories }}; do
                echo "Downloading from $repo"
                gh release download ${{ github.event.inputs.release-tag }} -R $repo -D ./projects/reports --clobber
              done
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          - name: Extract zip files into folders with cleaned base name
            run: |
              cd ./projects/reports
              for f in *.zip; do
                folder_name=$(echo "${f%.*}" | sed -E 's/(_ORIGINAL|_A|_B|_C\+?|_D)$//')
                unzip -o -d "$folder_name" "$f"
              done
              ls -l
    
          - name: Generate report csv
            run: |
              cd ./projects/reports
    
              # move ../../../scripts/parse_reports.py and sanity_check.py to ./projects/reports
              cp ../../scripts/parse_reports.py .
              cp ../../scripts/sanity_check.py .

              ls -l

              python3 parse_reports.py

              echo "================================== Results =================================="
              cat results.csv

              python3 sanity_check.py
              echo "========================= Results after Sanity check ========================"
              cat results.csv
    
            shell: bash
            continue-on-error: true
    
          - name: Upload report to GitHub Release
            uses: Wandalen/wretry.action@master
            with:
              attempt_delay: 60000 # 1 min
              attempt_limit: 10
              action: softprops/action-gh-release@v1
              with: |
                files: |
                  ./projects/reports/results.csv
                  ./projects/reports/new-results.csv
                tag_name: all-results-${{inputs.release-tag}}
                name: all-results-${{inputs.release-tag}}
                draft: false
                prerelease: true
                token: ${{ secrets.GITHUB_TOKEN }}
