name: Dependent Jobs Workflow
on:
  workflow_call:
    inputs:
      jobName:
        required: true
        type: string

jobs:
  dependent_jobs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: ['1', '2']
    steps:
      - name: Execute dependent job
        run: |
          echo "Running dependent job ${{ inputs.jobName }}${{ matrix.job }}"
