name: Find Repos Using Spec RegEx

permissions: 
  pull-requests: write
  contents: write

on:
  workflow_dispatch:
    inputs:
      testFramework:
        description: space delimited list of testing frameworks to find in manifest files (the list is ORed)
        default: 'pytest unit'
      start_page:
        description: the page to start collecting data from
        type: number
      end_page:
        description: the page to end collecting data at
        type: number
      start_spec:
        description: the spec to start collecting data from
        type: number
        default: 0
      end_spec:
        description: the spec to end collecting data at
        type: number
        default: 160

jobs:
  distribute-load:
    runs-on: ubuntu-latest
    outputs:
      ranges: ${{ steps.distribute-load.outputs.ranges }}
    steps:
      - id: distribute-load
        name: Distribute Load
        run: |
          RANGES=$(python3 -c "print([{'start': i, 'end': min(i + 10, ${{inputs.end_spec}})} for i in range(${{inputs.start_spec}}, ${{inputs.end_spec}}, 10)])")
          echo "RANGES: $RANGES"
          echo "ranges=${RANGES}" >> $GITHUB_OUTPUT
  crawl:
    permissions: 
      pull-requests: write
      contents: write

    needs: distribute-load
    runs-on: ubuntu-latest
    strategy:
      matrix:
        range: ${{ fromJson(needs.distribute-load.outputs.ranges) }}
      fail-fast: false
      max-parallel: 1
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install Dependencies
        run: yarn install

      - name: artificial delay to avoid rate limit
        run: sleep 60

      - name: Find Repos
        run: yarn start gh spec_id_basec_collect -t ${{inputs.testFramework}} -s ${{inputs.start_page}} -e ${{inputs.end_page}} -c ${{matrix.range.start}} -d ${{matrix.range.end}}
        timeout-minutes: 295
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          commit-message: "data: add found repos"
          branch: gh-repo-data-${{github.run_id}}
          title: "data: add found GitHub repos"
          body: "This PR adds more GitHub repo data."