name: Orchestrate Workflow Runs

on:
    workflow_dispatch:
      inputs:
        google_sheet_id:
          description: 'ID of the Google Sheet containing repository links.'
          required: true
        links_tab_name:
          description: 'Title of the tab containing the links.'
          required: true
        github_repositories:
          description: 'Space-separated list of GitHub repositories in the format owner/repo-name.'
          required: true

jobs:
    prepare-and-trigger:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
  
      - name: Install jq
        run: sudo apt-get install jq
  
      - name: Fetch Repository Links
        id: fetch-repos
        uses: jroehl/gsheet.action@v2.0.0
        with:
          spreadsheetId: ${{ github.event.inputs.google_sheet_id }}
          commands: |
            [
              {
                "command": "getData",
                "args": {
                  "worksheetTitle": "${{ github.event.inputs.links_tab_name }}",
                  "range": "${{ github.event.inputs.links_tab_name }}!A1:A"
                }
              }
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
  
      - name: Prepate links and github repos
        id: encode-decode
        run: |
          # Base64 encode the results to avoid shell parsing issues
          ENCODED_RESULTS=$(echo '${{ steps.fetch-repos.outputs.results }}' | base64)
          # Decode and parse using jq
          JSON_STRING=$(echo "$ENCODED_RESULTS" | base64 --decode | jq -c '[.results[].result.rawData[][]]')
          echo "Extracted JSON String:"
          echo "$JSON_STRING"
          echo "$JSON_STRING" > links.json
          cat links.json
          echo "${{ github.event.inputs.github_repositories }}" > github_repos.txt
  
      - name: Prepare Chunk Commands
        id: prepare-chunk-commands
        run: python3 scripts/manage_links.py
        env:
            GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
  
      - name: Create and Populate Tabs
        uses: jroehl/gsheet.action@v2.0.0
        with:
          spreadsheetId: ${{ github.event.inputs.google_sheet_id }}
          commands: ${{ steps.prepare-chunk-commands.outputs.commands }}
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
  
      - name: Trigger Workflows
        run: python3 scripts/trigger_workflows.py
  