name: Run Single Generated Tests

on:
  workflow_call:
    inputs:
      project-link:
        required: true
        type: string
      release-name:
        required: true
        type: string
    secrets: 
      GH_ACCESS_TOKEN:
        required: true 
jobs:
  run-original:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
    
        - name: Prepare Working Directory
          run: |
              mkdir ./projects
              cd ./projects
    
        - name: Setup variables
          run: |
              # Extract the repository URL from the input by removing any part after a semicolon
              REPO_URL=$(echo "${{ inputs.project-link }}" | sed 's/;.*//')
              # Extract the SHA from the input by removing any part before a semicolon
              SHA=$(echo "${{ inputs.project-link }}" | sed 's/.*;//')

              REPO_NAME="${REPO_URL##*/}"  # This strips everything before the last '/' character
              OWNER_NAME="${REPO_URL%/$REPO_NAME}"  # Removes the repo name from the URL, leaving the owner path
              OWNER_NAME="${OWNER_NAME##*/}"  # Extracts only the owner name
              FULL_REPO_NAME="$OWNER_NAME-$REPO_NAME"  # Combines owner and repository names with a dash
              ZIP_FILE="${FULL_REPO_NAME}.zip"

              echo "ZIP_FILE=$ZIP_FILE" >> $GITHUB_ENV
              echo "REPO_URL=$REPO_URL" >> $GITHUB_ENV
              echo "SHA=$SHA" >> $GITHUB_ENV
          shell: bash
        
        - name: Prepare working directory
          run: |
            mkdir -p ./projects
            cd ./projects
        
        - name: Run the project tests
          run: |
            cd ./projects
            cp ../scripts_pynguin/run_tests/run_tests.sh .
            chmod +x ./run_tests.sh
            ./run_tests.sh ${{env.REPO_URL}}
          shell: bash

        - name: Print contents of ./projects
          run: |
            cd ./projects
            # recursively print all the files in the directory 
            find . -type f
        
        - name: Zip report files
          run: |
            cd ./projects
            zip -r ../$ZIP_FILE .  # Create a zip file in the projects directory
            ls -l ../
          shell: bash

        - name: Upload report to GitHub Release
          uses: Wandalen/wretry.action@master
          with:
            attempt_delay: 60000 # 1 min
            attempt_limit: 10
            action: softprops/action-gh-release@v1
            with: |
              files: ./${{env.ZIP_FILE}}
              tag_name: ${{ inputs.release-name }}
              name: ${{ inputs.release-name }}
              draft: false
              prerelease: true
              token: ${{ secrets.GITHUB_TOKEN }}
