name: Scan Docs

on:
  workflow_dispatch:
    inputs:
      inFile:
        type: string
        required: true

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install Dependencies
        run: yarn install

      - name: Crawl Documentation
        run: yarn start docs -l out/docs/${{inputs.inFile}}
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "data: add crawled docs"
          branch: docs-data
          title: "data: add crawled docs"
          body: "This PR adds more crawled docs."