name: 'Get sys info'

on:
  workflow_dispatch:

jobs:
  print-sys-data:
    runs-on: ubuntu-latest
    steps:
      - run: |
          lscpu

          sudo dmidecode | grep Size | grep MB
        
          free -h 
          
          cat /proc/cpuinfo
          
          lsb_release -a
          
          hostnamectl
          
          df -h


