name: Time Experiment

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      with-class-count:
        description: 'Number of classes to be used in the experiment.'
        type: choice
        options:
          - true
          - false

jobs:
  run-original:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
    
        - name: Prepare Working Directory
          run: |
              mkdir ./projects
              cd ./projects
    
        - name: clone SoftEngResearch/mop-with-dynapt
          run: |
            cd ./projects
            git clone https://${{ secrets.GH_ACCESS_TOKEN }}@github.com/SoftEngResearch/mop-with-dynapt.git
            cd mop-with-dynapt
            git checkout add_statistics_new
            pip3 install .
    
        - name: Run the experiment
          run: |
            cd ./projects/mop-with-dynapt
            cp ../../time-experiment/* .
            ls -l

            chmod +x ./time-experiment.sh
            chmod +x ./time-experiment-with-classes.sh

            # if with-class-count is false 
            if [ "${{ github.event.inputs.with-class-count }}" == "false" ]; then
                ./time-experiment.sh
            else
                ./time-experiment-with-classes.sh
            fi

            # print the results
            cat time-experiment-results.csv
    
        - name: Upload report to GitHub Release
          uses: softprops/action-gh-release@v1
          with:
            files: ./projects/mop-with-dynapt/time-experiment-results.csv
            tag_name: time-experiment-${{github.run_id}}
            name: time-experiment-${{github.run_id}}
            draft: false
            prerelease: true
            token: ${{ secrets.GITHUB_TOKEN }}
