name: Time Experiment

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      algorithms:
        description: 'Algorithms to be used in the experiment.'
        type: string
        required: false
        default: 'A B C C+ D'
      instance_count:
        description: 'Number of instances to be used in the experiment.'
        type: string
        required: false
        default: '10 50 100'
      event_count:
        description: 'Number of events to be used in the experiment.'
        type: string
        required: false
        default: '5 10 20'
      creation_event_percent:
        description: 'Percentage of creation events to be used in the experiment.'
        type: string
        required: false
        default: '20 60 100'
      enable_event_percent:
        description: 'Percentage of enable events to be used in the experiment.'
        type: string
        required: false
        default: '20 60 100'
      file_name:
        description: 'Name of the file to be used in the experiment.'
        type: choice
        required: false
        default: 'FakeSpec.py'
        options:
          - 'FakeSpec.py'
          - 'StringTemplate.py'
          - 'UnsafeMapIterator.py'

jobs:
  run-original:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
    
        - name: Prepare Working Directory
          run: |
              mkdir ./projects
              cd ./projects
    
        - name: clone SoftEngResearch/mop-with-dynapt
          run: |
            cd ./projects
            git clone https://${{ secrets.GH_ACCESS_TOKEN }}@github.com/SoftEngResearch/mop-with-dynapt.git
            cd mop-with-dynapt
            git checkout add_statistics_new
            pip3 install .
    
        - name: Run the experiment
          run: |
            cd ./projects/mop-with-dynapt
            cp ../../time-experiment/* .
            ls -l

            chmod +x ./time-experiment.sh
            chmod +x ./time-experiment-with-classes.sh

            ./time-experiment.sh ${{ inputs.algorithms }} ${{ inputs.instance_count }} ${{ inputs.event_count }} ${{ inputs.creation_event_percent }} ${{ inputs.enable_event_percent }} ${{ inputs.file_name }}

            # print the results
            cat time-experiment-results.csv
    
        - name: Upload report to GitHub Release
          uses: softprops/action-gh-release@v1
          with:
            files: ./projects/mop-with-dynapt/time-experiment-results.csv
            tag_name: time-experiment-${{github.run_id}}
            name: time-experiment-${{github.run_id}}
            draft: false
            prerelease: true
            token: ${{ secrets.GITHUB_TOKEN }}
