name: Time Experiment

on:
  workflow_dispatch:

jobs:
  run-original:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
    
        - name: Prepare Working Directory
          run: |
              mkdir ./projects
              cd ./projects
    
        - name: clone SoftEngResearch/mop-with-dynapt
          run: |
            cd ./projects
            git clone https://${{ secrets.GH_ACCESS_TOKEN }}@github.com/SoftEngResearch/mop-with-dynapt.git
            cd mop-with-dynapt
            git checkout add_statistics_new
            pip3 install .
    
        - name: Run the experiment
          run: |
            cd ./projects/mop-with-dynapt
            cp ../../time-experiment/* .
            ls -l

            chmod +x ./time-experiment.sh
            ./time-experiment.sh
    
        - name: Upload report to GitHub Release
          uses: Wandalen/wretry.action@master
          with:
            attempt_delay: 60000 # 1 min
            attempt_limit: 10
            action: softprops/action-gh-release@v1
            with: |
              files: ./projects/mop-with-dynapt/time-experiment-results.csv
              tag_name: time-experiment-${{github.run_id}}
              name: time-experiment-${{github.run_id}}
              draft: false
              prerelease: true
              token: ${{ secrets.GITHUB_TOKEN }}
